// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package funccli

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// EnsureReady provides a mock function for the type MockManager
func (_mock *MockManager) EnsureReady(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for EnsureReady")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_EnsureReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureReady'
type MockManager_EnsureReady_Call struct {
	*mock.Call
}

// EnsureReady is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManager_Expecter) EnsureReady(ctx interface{}) *MockManager_EnsureReady_Call {
	return &MockManager_EnsureReady_Call{Call: _e.mock.On("EnsureReady", ctx)}
}

func (_c *MockManager_EnsureReady_Call) Run(run func(ctx context.Context)) *MockManager_EnsureReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_EnsureReady_Call) Return(err error) *MockManager_EnsureReady_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_EnsureReady_Call) RunAndReturn(run func(ctx context.Context) error) *MockManager_EnsureReady_Call {
	_c.Call.Return(run)
	return _c
}

// GetBinaryPath provides a mock function for the type MockManager
func (_mock *MockManager) GetBinaryPath() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBinaryPath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_GetBinaryPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBinaryPath'
type MockManager_GetBinaryPath_Call struct {
	*mock.Call
}

// GetBinaryPath is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetBinaryPath() *MockManager_GetBinaryPath_Call {
	return &MockManager_GetBinaryPath_Call{Call: _e.mock.On("GetBinaryPath")}
}

func (_c *MockManager_GetBinaryPath_Call) Run(run func()) *MockManager_GetBinaryPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetBinaryPath_Call) Return(s string, err error) *MockManager_GetBinaryPath_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockManager_GetBinaryPath_Call) RunAndReturn(run func() (string, error)) *MockManager_GetBinaryPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentVersion provides a mock function for the type MockManager
func (_mock *MockManager) GetCurrentVersion(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentVersion")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_GetCurrentVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentVersion'
type MockManager_GetCurrentVersion_Call struct {
	*mock.Call
}

// GetCurrentVersion is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManager_Expecter) GetCurrentVersion(ctx interface{}) *MockManager_GetCurrentVersion_Call {
	return &MockManager_GetCurrentVersion_Call{Call: _e.mock.On("GetCurrentVersion", ctx)}
}

func (_c *MockManager_GetCurrentVersion_Call) Run(run func(ctx context.Context)) *MockManager_GetCurrentVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_GetCurrentVersion_Call) Return(s string, err error) *MockManager_GetCurrentVersion_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockManager_GetCurrentVersion_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockManager_GetCurrentVersion_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockManager
func (_mock *MockManager) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockManager_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManager_Expecter) Start(ctx interface{}) *MockManager_Start_Call {
	return &MockManager_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockManager_Start_Call) Run(run func(ctx context.Context)) *MockManager_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_Start_Call) Return(err error) *MockManager_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_Start_Call) RunAndReturn(run func(ctx context.Context) error) *MockManager_Start_Call {
	_c.Call.Return(run)
	return _c
}
